server:
  port: 8082
spring:
  application:
    name: client_module
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tribuna90

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URI:http://localhost:8761/eureka}

app:
  ingreso:
    intentos: 3

logging:
  level:
    root: INFO